services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  xximing/dsci522-car-evaluation:82e80c5
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
