name: car_evaluation_analysis
channels:
  - conda-forge
dependencies:
  - python=3.11.6
  - pip=24.3.1
  - pandas=2.1.2
  - numpy=1.26.0
  - matplotlib=3.8.0
  - scikit-learn=1.3.2
  - altair=5.1.2
  - vegafusion=1.4.3
  - vegafusion-jupyter=1.4.3
  - vegafusion-python-embed=1.4.3
  - vl-convert-python=1.0.1
  - ipykernel=6.26.0
  - notebook=6.5.4
  - jupyterlab=4.0.5
  - jupyter_contrib_nbextensions=0.7.0
  - requests=2.31.0
  - pandera=0.17.1
  - pydantic=1.10.12
  - click=8.1.7