---
title: "Predicting Level of Acceptability of Cars"
author: "Danish Karlin Isa, Nicholas Varabioff, Ximin Xu & Zuer Zhong"
date: today
format: revealjs
jupyter: python3
---

# Introduction

## Car Evaluation Data Target

Created by the efforts of M. Bohanec in the late 1980s

### Acceptability

1. `unacc`: Unacceptable. Cars that fail to meet basic criteria.
2. `acc`: Acceptable. Cars that meet minimum requirements.
3. `good`: Good. Cars that exceed average standards in some aspects.
4. `vgood`: Very good. Cars that meet the highest standards.

## Car Evaluation Data Features

Created by the efforts of M. Bohanec in the late 1980s

| Feature Name | Data Type | Values |
| ------------ | --------- | ------ |
| `buying` | Categorical | `low`, `med`, `high`, `vhigh` |
| `maint` | Categorical | `low`, `med`, `high`, `vhigh` |
| `doors` | Categorical | `2`, `3`, `4`, `5more` |
| `persons` | Categorical | `2`, `4`, `more` |
| `lug_boot` | Categorical | `small`, `med`, `big` |
| `safety` | Categorical | `low`, `med`, `high` |

# Exploratory data analysis

Rebecca's part goes here

# Selecting our model

```{python}
# imports
import pandas as pd
from IPython.display import Markdown, display
from tabulate import tabulate

model_selection_results = pd.read_csv("results/tables/model_selection_results.csv").round(3)
```

## Shortlisting models from `sklearn`

| Type | Model |
| ---- | ----- |
| Baseline | `DummyClassifier` |
| Tree-based |  `DecisionTreeClassifier` |
| Distance-based | `KNearestNeighbors` |
| Hyperplanes | `SVC` |
| Probabilistic | `MultinomialNB` |
| Regression | `LogisticRegression` |

## Accuracy scores with cross-validation {.smaller}

```{python}
Markdown(model_selection_results.to_markdown(index=False))
```

## The chosen model: `SVC`

Finding hyperplane that best separates the different classes (`quality`)

* "Curved" hyperplanes great for overlapping features

* Shorter `predict` times (versus `KNearestNeighbors`)

* Less susceptible to overfitting (versus `DecisionTreeClassifier`)

# Model tuning

Ximin's part goes here